all: listing1 listing2 listing3 listing5

listing1:
	g++ -std=c++23 -o listing1 listing1.cpp

listing2:
	g++ -std=c++23 -o listing2 listing2.cpp

listing3:
	g++ -std=c++23 -o listing3 listing3.cpp

listing5:
	g++ -std=c++23 -o listing5 listing5.cpp

clean:	
	rm -f listing?
