all:	mm1 mm2 mm3 mm4 mm5 mm6 exercise01 exercise02

mm1:	mm1.cpp
	g++ -std=c++23 -o mm1 mm1.cpp

mm2:	mm2.cpp
	g++ -std=c++23 -o mm2 mm2.cpp

mm3:	mm3.cpp
	g++ -std=c++23 -o mm3 mm3.cpp

mm4:	mm4.cpp
	g++ -std=c++23 -o mm4 mm4.cpp

mm5:	mm5.cpp
	g++ -std=c++23 -o mm5 mm5.cpp

mm6:	mm6.cpp
	g++ -std=c++23 -o mm6 mm6.cpp

exercise01: exercise01.cpp 	
	g++ -std=c++23 -o exercise01 exercise01.cpp

exercise02: exercise02.cpp 	
	g++ -std=c++23 -o exercise02 exercise02.cpp

clean: 
	rm -f *.o mm1 mm2 mm3 mm4 mm5 mm6 exercise01 exercise02
