all:	*.cpp 
	g++ -std=c++20 -lpthread -o listing1 listing1.cpp 
	g++ -std=c++20 -lpthread -o listing2 listing2.cpp 
	g++ -std=c++20 -lpthread -o listing3 listing3.cpp 
	g++ -std=c++20 -lpthread -o listing4 listing4.cpp 
	g++ -std=c++20 -lpthread -o listing5 listing5.cpp 
	g++ -std=c++20 -lpthread -o exercise01 exercise01.cpp 
	g++ -std=c++20 -lpthread -o exercise02 exercise02.cpp 
	g++ -std=c++20 -lpthread -o thread_local1 thread_local1.cpp 
	g++ -std=c++20 -lpthread -o thread_local2 thread_local2.cpp 
	g++ -std=c++20 -lpthread -o dining_philosophers dining_philosophers.cpp 
	g++ -std=c++20 -lpthread -o count count.cpp 
	g++ -std=c++20 -lpthread -o count_native count_native.cpp 
	
clean: 
	rm listing1 listing2 listing3 listing4 listing5 thread_local1 thread_local2 dining_philosophers exercise01 exercise02 count count_native
