all: exercise01 exercise02 exercise03 exercise04 exercise05 exercise06 exercise07 exercise08 exercise09 exercise10 exercise11 listing1 listing2 listing3 listing4 listing5 listing6


exercise01:
	g++ -std=c++20 -o exercise01 exercise01.cpp


exercise02:
	g++ -std=c++20 -o exercise02 exercise02.cpp


exercise03:
	g++ -std=c++20 -o exercise03 exercise03.cpp


exercise04:
	g++ -std=c++20 -o exercise04 exercise04.cpp


exercise05:
	g++ -std=c++20 -o exercise05 exercise05.cpp


exercise06:
	g++ -std=c++20 -o exercise06 exercise06.cpp


exercise07:
	g++ -std=c++20 -o exercise07 exercise07.cpp


exercise08:
	g++ -std=c++20 -o exercise08 exercise08.cpp


exercise09:
	g++ -std=c++20 -o exercise09 exercise09.cpp


exercise10:
	g++ -std=c++20 -o exercise10 exercise10.cpp


exercise11:
	g++ -std=c++20 -o exercise11 exercise11.cpp


listing1:
	g++ -std=c++20 -o listing1 listing1.cpp


listing2:
	g++ -std=c++20 -o listing2 listing2.cpp

listing3:
	g++ -std=c++20 -o listing3 listing3.cpp

listing4:
	g++ -std=c++20 -o listing4 listing4.cpp

listing5:
	g++ -std=c++20 -o listing5 listing5.cpp

listing6:
	g++ -std=c++20 -o listing6 listing6.cpp

clean:	
	rm -f exercise?? listing?
