all: exercise01 exercise02 exercise03 exercise04 listing1 listing2 listing3 listing4 listing5 listing6 listing7 listing8 listing9 barrier bitfield1

exercise01:
	g++ -std=c++20 -o exercise01 exercise01.cpp

bitfield1:
	g++ -std=c++20 -o bitfield1 bitfield1.cpp

barrier:
	g++ -std=c++20 -o barrier barrier.cpp

exercise02:
	g++ -std=c++20 -o exercise02 exercise02.cpp


exercise03:
	g++ -std=c++20 -o exercise03 exercise03.cpp


exercise04:
	g++ -std=c++20 -o exercise04 exercise04.cpp


listing1:
	g++ -std=c++20 -o listing1 listing1.cpp

listing2:
	g++ -std=c++20 -o listing2 listing2.cpp

listing3:
	g++ -std=c++20 -o listing3 listing3.cpp

listing4:
	g++ -std=c++20 -o listing4 listing4.cpp

listing5:
	g++ -std=c++20 -o listing5 listing5.cpp

listing6:
	g++ -std=c++20 -o listing6 listing6.cpp

listing7:
	g++ -std=c++20 -o listing7 listing7.cpp

listing8:
	g++ -std=c++20 -o listing8 listing8.cpp

listing9:
	g++ -std=c++20 -o listing9 listing9.cpp

clean:	
	rm -f exercise?? listing? bitfield1 barrier
