all:	*.cpp 
	g++ -std=c++20 -lpthread -o example1 example1.cpp 
	g++ -std=c++20 -lpthread -o example2 example2.cpp 
	g++ -std=c++20 -lpthread -o example3 example3.cpp 	
	g++ -std=c++20 -lpthread -o example4 example4.cpp 
	g++ -std=c++20 -lpthread -o listing1 listing1.cpp 
	g++ -std=c++20 -lpthread -o listing2 listing2.cpp 
	g++ -std=c++20 -lpthread -o listing3 listing3.cpp 
	g++ -std=c++20 -lpthread -o listing4 listing4.cpp 
	g++ -std=c++20 -lpthread -o listing5 listing5.cpp 
	g++ -std=c++20 -lpthread -o listing6 listing6.cpp 
	g++ -std=c++20 -lpthread -o listing7 listing7.cpp 
	g++ -std=c++20 -lpthread -o listing8 listing8.cpp 
	g++ -std=c++20 -lpthread -o number_of_cores number_of_cores.cpp 
	g++ -std=c++20 -lpthread -o exercise01 exercise01.cpp 
	g++ -std=c++20 -lpthread -o exercise02 exercise02.cpp 
	g++ -std=c++20 -lpthread -o exercise03 exercise03.cpp 
	g++ -std=c++20 -lpthread -o exercise04 exercise04.cpp 
	g++ -std=c++20 -lpthread -o exercise05 exercise05.cpp 
	g++ -std=c++20 -lpthread -o exercise06 exercise06.cpp 
	g++ -std=c++20 -lpthread -o exercise07 exercise07.cpp 
	g++ -std=c++20 -lpthread -o exercise08 exercise08.cpp 
	g++ -std=c++20 -lpthread -o exercise09 exercise09.cpp 
	
clean: 
	rm example1 example2 example3 example4 listing1 listing2 listing3 listing4 listing5 listing6 listing7 listing8 number_of_cores exercise01 exercise02 exercise03 exercise04 exercise05 exercise06 exercise07 exercise08 exercise09
