all:	exercise01 \
	exercise02 \
	exercise03 \
	exercise04 \
	exercise05 \
	exercise06 \
	exercise07 \
	exercise08 \
	exercise09 

clean:	
	rm -f exercise01 exercise02 exercise03 exercise04 exercise05 exercise06 exercise07 exercise08 exercise09 
